language: python
python:
  - "3.4"
  - "3.5"
# command to install dependencies
install:
  - sudo apt-get install python-pip
  - sudo /usr/bin/pip install -U pytest
  - pip install -r requirements/development.txt
  - pip install coveralls
# command to run tests
script:
  - coverage run --source=bingmaps -m py.test tests
  - coverage report -m
# commands to run setup file
# commands to run some style (pep8, pylint) tests on
# the package
after_success:
# commands to run after tests
  - coveralls